version: "3.9"
services:
    api:
        build: 
          context: .
          dockerfile: api/Dockerfile
        ports:
            - "5001:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "password123*"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"